name: "Mirror"

on:
  - push

env:
  owner: "${{ github.repository_owner }}-mirror"
  domain: "https://codeberg.org"
  version: "v1"

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: "Codeberg"
    steps:
      - name: "Get repository name"
        shell: bash
        run: |
          echo "repo_name=$( echo '${{ github.repository }}' | awk -F '/' '{ print $2 }' )" >> $GITHUB_ENV
      - name: "Create repository"
        shell: bash
        run: |
          http="$( curl -s -o '/dev/null' -I -w '%{http_code}' -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36' '${{ env.domain }}/${{ env.owner }}/${{ env.repo_name }}' )"
          if [[ "${http}" -ne 200 ]]; then
            curl -X POST \
            -H 'Authorization: token ${{ secrets.BOT_CODEBERG_TOKEN }}' \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36' \
            '${{ env.domain }}/api/${{ env.version }}/orgs/${{ env.owner }}/repos' \
            -d '{"name":"${{ env.repo_name }}"}'
          fi
      - name: "Mirror repository"
        uses: ghastore/mirror@main
        with:
          src_repo: "${{ github.server_url }}/${{ github.repository }}.git"
          src_user: "${{ secrets.BOT_GITHUB_NAME }}"
          src_token: "${{ secrets.BOT_GITHUB_TOKEN }}"
          dst_repo: "${{ env.domain }}/${{ env.owner }}/${{ env.repo_name }}.git"
          dst_user: "${{ secrets.BOT_CODEBERG_NAME }}"
          dst_token: "${{ secrets.BOT_CODEBERG_TOKEN }}"
